# Generated by Django 5.2.7 on 2026-02-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(choices=[('Poultry', 'Poultry'), ('Cattle', 'Cattle'), ('Goat', 'Goat'), ('Pet', 'Pet'), ('Others', 'Others')], max_length=20),
        ),
    ]
