# Generated by Django 5.2.7 on 2026-02-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='purchase',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
