# Generated by Django 5.2.7 on 2026-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_purchase_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='price',
        ),
        migrations.AddField(
            model_name='feed',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='feed',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='feed',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
