# Generated by Django 5.2.7 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_feed_price_feed_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='feed',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
